# Generated by Django 4.2.1 on 2023-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
