# Generated by Django 4.2.1 on 2023-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="exam_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="exam_withdrawal",
            field=models.BooleanField(default=False),
        ),
    ]
